import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "en" | "ar" | "ru" | "uk" | "ro" | "pl" | "it" | "tr" | "fr" | "de" | "nl";
export type SiteId = "texafab" | "fincore" | "dubai-stroy" | "nextrev" | "exchange";

export const languageNames: Record<Language, string> = {
  en: "English",
  ar: "العربية",
  fr: "Français",
  de: "Deutsch",
  nl: "Nederlands",
  it: "Italiano",
  tr: "Türkçe",
  ru: "Русский",
  uk: "Українська",
  ro: "Română",
  pl: "Polski",
};

export const rtlLanguages: Language[] = ["ar"];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
  isRTL: boolean;
  siteId: SiteId;
  setSiteId: (id: SiteId) => void;
}

// Language context with default fallback support
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.features": "Features",
    "nav.pricing": "Pricing",
    "nav.contact": "Contact",
    "nav.becomeAgent": "Become an Agent",
    "nav.solutions": "Solutions",
    "nav.industries": "Industries",
    "nav.about": "About",
    "nav.whyTexaCore": "Why TexaCore?",
    "nav.workflow": "Workflow",
    "nav.viewAllSolutions": "View All Solutions",
    "nav.signIn": "Sign In",
    "nav.startFree": "Start Free",
    "nav.selectLanguage": "Select Language",
    "nav.selectTheme": "Select Theme",
    // Solution Links
    "solutions.containerTracking": "Container Tracking",
    "solutions.rollManagement": "Roll Management",
    "solutions.warehouseManagement": "Warehouse Management",
    "solutions.fabricManagement": "Fabric Management",
    "solutions.posSystem": "POS System",
    "solutions.completeWorkflow": "Complete Workflow",
    "solutions.ecommerce": "E-Commerce",
    "solutions.crm": "CRM",
    "solutions.employeeManagement": "Employee Management",
    "solutions.accounting": "Accounting & Profits",
    "solutions.fabricManufacturing": "Fabric Manufacturing",
    "solutions.garmentManufacturing": "Garment Manufacturing",
    "solutions.aiAnalytics": "AI & Analytics",
    "solutions.reportsAnalytics": "Reports & Analytics",
    "solutions.shipping": "Shipping & Delivery",
    "solutions.agentsDealers": "Agents & Dealers",
    // Theme
    "theme.light": "Light",
    "theme.dark": "Dark",
    "theme.auto": "Auto",
    // Hero
    "hero.title": "First ERP System For Fabric Industry",
    "hero.subtitle": "The world's first system designed specifically for fabric companies. Supports meters, rolls, colors, cutting, and everything you need.",
    "hero.cta.demo": "Start Free Trial",
    "hero.cta.trial": "Watch Demo",
    "hero.badge": "First Choice in Europe & Gulf",
    "hero.tagline": "Quality Worth Trusting",
    "hero.noCreditCard": "No credit card",
    "hero.quickSetup": "Quick setup",
    "hero.arabicSupport": "Arabic support",
    // Hero Stats
    "hero.stat.companies": "Fabric Companies",
    "hero.stat.rolls": "Rolls Tracked",
    "hero.stat.countries": "Countries",
    "hero.stat.industry": "In Fabric Industry",
    // Hero Features
    "hero.feature.meters": "Meters",
    "hero.feature.rolls": "Rolls",
    "hero.feature.colors": "Colors",
    "hero.feature.cutting": "Cutting",
    "hero.feature.warehouses": "Warehouses",
    "hero.feature.accounting": "Accounting",
    // Dashboard Preview
    "hero.dashboard.revenue": "Revenue",
    "hero.dashboard.expenses": "Expenses",
    "hero.dashboard.profit": "Profit",
    "hero.dashboard.cash": "Cash",
    "hero.dashboard.cashFlow": "Cash Flow",
    "hero.dashboard.orders": "Orders",
    // Features
    "features.title": "Everything You Need",
    "features.subtitle": "Complete ERP system covering all your business needs.",
    "features.allFeatures": "All Features",
    "features.headerTitle": "Everything You Need in One System",
    "features.headerSubtitle": "Complete ERP system covering all your business needs from accounting to inventory and sales management",
    "features.exploreAll": "Explore All Features",
    // Features Items
    "features.barcode.title": "Advanced Barcode",
    "features.barcode.desc": "Unique barcode for each roll with complete tracking from import to sale.",
    "features.barcode.stat": "Full Tracking",
    "features.color.title": "Color Management",
    "features.color.desc": "Fabric classification by color and shade with precise sample matching.",
    "features.color.stat": "Smart Matching",
    "features.fabric.title": "Fabric by Meter & Roll",
    "features.fabric.desc": "Supports all measurement units: meter, roll, yard, kilo with auto conversion.",
    "features.fabric.stat": "Auto Conversion",
    "features.warehouse.title": "Multi-Warehouse",
    "features.warehouse.desc": "Manage multiple warehouses with shelf location for each roll.",
    "features.warehouse.stat": "Full Tracking",
    "features.accounting.title": "Full Accounting",
    "features.accounting.desc": "Complete accounting system designed for fabric trade with multi-currency.",
    "features.accounting.stat": "Financial Reports",
    "features.ecommerce.title": "E-commerce Store",
    "features.ecommerce.desc": "Ready e-commerce store with NO design or setup fees included.",
    "features.ecommerce.stat": "No Extra Fees",
    // Additional Features
    "features.reports": "Reports",
    "features.payments": "Payments",
    "features.branches": "Branches",
    "features.analytics": "Analytics",
    // Trust
    "trust.title": "Why TexaCore?",
    // Pricing
    "pricing.title": "Choose Your Plan",
    // Footer
    "footer.rights": "© 2024 TexaCore. All rights reserved.",
    // CTA
    "cta.ready": "Ready to Get Started?",
    "cta.button": "Start Free Trial",
    "cta.digitalTransformation": "Start Your Digital Transformation",
    "cta.joinCompanies": "Join 500+ companies using TexaCore to manage their business efficiently",
    "cta.benefit1": "14-day free trial",
    "cta.benefit2": "No credit card required",
    "cta.benefit3": "Full feature access",
    "cta.contactSales": "Contact Sales",
    // Footer
    "footer.transformBusiness": "Ready to Transform Your Business Operations?",
    "footer.trustCompanies": "Join 500+ companies that trust TexaCore for their business management",
    "footer.schedulDemo": "Schedule Demo",
    "footer.description": "Complete cloud ERP system designed for modern enterprises. Trusted by 500+ companies.",
    "footer.product": "Product",
    "footer.solutions": "Solutions",
    "footer.company": "Company",
    "footer.resources": "Resources",
    "footer.newsletter": "Stay Updated",
    "footer.emailPlaceholder": "Your email",
    "footer.location": "Dublin, Ireland",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.faq": "FAQ",
    "footer.news": "News & Updates",
    "footer.about": "About Us",
    "footer.developedBy": "All TexaCore developments by",
    "footer.nextRevolutionTagline": "Global Software Solutions from Ireland — Serving Enterprises Worldwide",
    // Global
    "global.learnMore": "Learn More",
    "global.getStarted": "Get Started",
    "global.contactUs": "Contact Us",
    "global.startFree": "Start Free",
    "global.bookDemo": "Book Demo",
    // Floating Button
    "floating.boostSales": "Boost Sales 70%",
    "floating.seeTheDifference": "See the difference",
  },
  ar: {
    // Navigation
    "nav.features": "الميزات",
    "nav.pricing": "الأسعار",
    "nav.contact": "تواصل معنا",
    "nav.becomeAgent": "كن وكيلاً",
    "nav.solutions": "الحلول",
    "nav.industries": "القطاعات",
    "nav.about": "عن الشركة",
    "nav.whyTexaCore": "لماذا \u200FTexaCore\u200F؟",
    "nav.workflow": "سير العمل",
    "nav.viewAllSolutions": "عرض جميع الحلول",
    "nav.signIn": "تسجيل الدخول",
    "nav.startFree": "ابدأ مجاناً",
    "nav.selectLanguage": "اختر اللغة",
    "nav.selectTheme": "اختر المظهر",
    // Solution Links
    "solutions.containerTracking": "تتبع الكونتينرات",
    "solutions.rollManagement": "إدارة الرولونات",
    "solutions.warehouseManagement": "إدارة المستودعات",
    "solutions.fabricManagement": "إدارة الأقمشة",
    "solutions.posSystem": "نقاط البيع",
    "solutions.completeWorkflow": "سير العمل المتكامل",
    "solutions.ecommerce": "المتجر الإلكتروني",
    "solutions.crm": "إدارة العملاء CRM",
    "solutions.employeeManagement": "إدارة الموظفين",
    "solutions.accounting": "المحاسبة والأرباح",
    "solutions.fabricManufacturing": "تصنيع الأقمشة",
    "solutions.garmentManufacturing": "تصنيع الألبسة",
    "solutions.aiAnalytics": "الذكاء الاصطناعي",
    "solutions.reportsAnalytics": "التقارير",
    "solutions.shipping": "الشحن والتوصيل",
    "solutions.agentsDealers": "الوكلاء والموزعين",
    // Theme
    "theme.light": "فاتح",
    "theme.dark": "داكن",
    "theme.auto": "تلقائي",
    // Hero
    "hero.title": "أول نظام ERP متخصص للأقمشة",
    "hero.subtitle": "النظام الأول عالمياً المصمم خصيصاً لشركات الأقمشة. يدعم المتر، الرولون، الألوان، القص، وكل ما تحتاجه.",
    "hero.cta.demo": "ابدأ مجاناً",
    "hero.cta.trial": "شاهد العرض",
    "hero.badge": "الاختيار الأول في أوروبا والخليج",
    "hero.tagline": "جودة تستحق الثقة",
    "hero.noCreditCard": "بدون بطاقة ائتمان",
    "hero.quickSetup": "إعداد سريع",
    "hero.arabicSupport": "دعم عربي",
    // Hero Stats
    "hero.stat.companies": "شركة أقمشة",
    "hero.stat.rolls": "رولون متتبع",
    "hero.stat.countries": "دولة",
    "hero.stat.industry": "في صناعة الأقمشة",
    // Hero Features
    "hero.feature.meters": "الأمتار",
    "hero.feature.rolls": "الرولونات",
    "hero.feature.colors": "الألوان",
    "hero.feature.cutting": "القص",
    "hero.feature.warehouses": "المستودعات",
    "hero.feature.accounting": "المحاسبة",
    // Dashboard Preview
    "hero.dashboard.revenue": "الإيرادات",
    "hero.dashboard.expenses": "المصاريف",
    "hero.dashboard.profit": "الربح",
    "hero.dashboard.cash": "التدفق",
    "hero.dashboard.cashFlow": "التدفق النقدي",
    "hero.dashboard.orders": "الطلبات",
    // Features
    "features.title": "كل ما تحتاجه",
    "features.subtitle": "نظام ERP متكامل يغطي جميع احتياجات عملك.",
    "features.allFeatures": "جميع الميزات",
    "features.headerTitle": "كل ما تحتاجه في نظام واحد",
    "features.headerSubtitle": "نظام ERP متكامل يغطي جميع احتياجات عملك من المحاسبة إلى إدارة المخزون والمبيعات",
    "features.exploreAll": "اكتشف جميع الميزات",
    // Features Items
    "features.barcode.title": "باركود متقدم",
    "features.barcode.desc": "باركود فريد لكل رولون مع تتبع كامل من الاستيراد للبيع.",
    "features.barcode.stat": "تتبع كامل",
    "features.color.title": "إدارة الألوان",
    "features.color.desc": "تصنيف الأقمشة حسب اللون والدرجة مع مطابقة دقيقة للعينات.",
    "features.color.stat": "مطابقة ذكية",
    "features.fabric.title": "إدارة الأقمشة بالمتر",
    "features.fabric.desc": "نظام فريد يدعم جميع وحدات القياس: المتر، الرولون، الياردة، الكيلو.",
    "features.fabric.stat": "تحويل تلقائي",
    "features.warehouse.title": "المستودعات المتعددة",
    "features.warehouse.desc": "إدارة مستودعات متعددة مع تحديد موقع الرف لكل رولون.",
    "features.warehouse.stat": "تتبع شامل",
    "features.accounting.title": "المحاسبة الكاملة",
    "features.accounting.desc": "نظام محاسبي متكامل مصمم لتجارة الأقمشة مع دعم العملات المتعددة.",
    "features.accounting.stat": "تقارير مالية",
    "features.ecommerce.title": "المتجر الإلكتروني",
    "features.ecommerce.desc": "متجر إلكتروني جاهز بدون رسوم تصميم أو تشغيل إضافية.",
    "features.ecommerce.stat": "بدون رسوم",
    // Additional Features
    "features.reports": "التقارير",
    "features.payments": "المدفوعات",
    "features.branches": "الفروع",
    "features.analytics": "التحليلات",
    // Trust
    "trust.title": "لماذا TexaCore؟",
    // Pricing
    "pricing.title": "اختر باقتك",
    // Footer
    "footer.rights": "© 2024 TexaCore. جميع الحقوق محفوظة.",
    // CTA
    "cta.ready": "جاهز للبدء؟",
    "cta.button": "ابدأ الآن",
    "cta.digitalTransformation": "ابدأ رحلة التحول الرقمي",
    "cta.joinCompanies": "انضم لأكثر من 500 شركة تستخدم TexaCore لإدارة أعمالها بكفاءة عالية",
    "cta.benefit1": "14 يوم تجربة مجانية",
    "cta.benefit2": "بدون بطاقة ائتمان",
    "cta.benefit3": "جميع الميزات متاحة",
    "cta.contactSales": "تواصل معنا",
    // Footer
    "footer.transformBusiness": "هل أنت جاهز لتحويل عملياتك التجارية؟",
    "footer.trustCompanies": "انضم لأكثر من 500 شركة تثق بـ TexaCore لإدارة أعمالها",
    "footer.schedulDemo": "احجز عرض توضيحي",
    "footer.description": "نظام ERP سحابي متكامل مصمم للشركات الحديثة. موثوق به من قبل أكثر من 500 شركة.",
    "footer.product": "المنتج",
    "footer.solutions": "الحلول",
    "footer.company": "الشركة",
    "footer.resources": "الموارد",
    "footer.newsletter": "اشترك في النشرة",
    "footer.emailPlaceholder": "بريدك الإلكتروني",
    "footer.location": "دبلن، أيرلندا",
    "footer.privacy": "سياسة الخصوصية",
    "footer.terms": "الشروط والأحكام",
    "footer.faq": "الأسئلة الشائعة",
    "footer.news": "الأخبار والتحديثات",
    "footer.about": "من نحن",
    "footer.developedBy": "جميع تطويرات TexaCore من",
    "footer.nextRevolutionTagline": "حلول برمجية عالمية من أيرلندا — نخدم المؤسسات حول العالم",
    // Global
    "global.learnMore": "اعرف المزيد",
    "global.getStarted": "ابدأ الآن",
    "global.contactUs": "تواصل معنا",
    "global.startFree": "ابدأ مجاناً",
    "global.bookDemo": "احجز عرض",
    // Floating Button
    "floating.boostSales": "زد مبيعاتك 70%",
    "floating.seeTheDifference": "اكتشف الفرق الآن",
  },
  ru: {
    // Navigation
    "nav.features": "Функции",
    "nav.pricing": "Цены",
    "nav.contact": "Контакт",
    "nav.becomeAgent": "Стать агентом",
    "nav.solutions": "Решения",
    "nav.industries": "Отрасли",
    "nav.about": "О нас",
    "nav.whyTexaCore": "Почему TexaCore?",
    "nav.workflow": "Процесс",
    "nav.viewAllSolutions": "Все",
    "nav.signIn": "Войти",
    "nav.startFree": "Начать бесплатно",
    "nav.selectLanguage": "Выбрать язык",
    "nav.selectTheme": "Выбрать тему",
    // Solution Links
    "solutions.containerTracking": "Отслеживание контейнеров",
    "solutions.rollManagement": "Управление рулонами",
    "solutions.warehouseManagement": "Управление складом",
    "solutions.fabricManagement": "Управление тканями",
    "solutions.posSystem": "POS система",
    "solutions.completeWorkflow": "Полный рабочий процесс",
    "solutions.ecommerce": "Интернет-магазин",
    "solutions.crm": "CRM",
    "solutions.employeeManagement": "Управление персоналом",
    "solutions.accounting": "Бухгалтерия и прибыль",
    "solutions.fabricManufacturing": "Производство тканей",
    "solutions.garmentManufacturing": "Производство одежды",
    "solutions.aiAnalytics": "ИИ и аналитика",
    "solutions.reportsAnalytics": "Отчёты и аналитика",
    "solutions.shipping": "Доставка",
    "solutions.agentsDealers": "Агенты и дилеры",
    // Theme
    "theme.light": "Светлая",
    "theme.dark": "Тёмная",
    "theme.auto": "Авто",
    // Hero
    "hero.title": "Первая ERP-система для текстильной отрасли",
    "hero.subtitle": "Первая в мире система, разработанная специально для текстильных компаний. Поддерживает метры, рулоны, цвета, раскрой.",
    "hero.cta.demo": "Начать бесплатно",
    "hero.cta.trial": "Смотреть демо",
    "hero.badge": "Первый выбор в Европе и Персидском заливе",
    "hero.tagline": "Качество, достойное доверия",
    "hero.noCreditCard": "Без банковской карты",
    "hero.quickSetup": "Быстрая настройка",
    "hero.arabicSupport": "Поддержка арабского",
    "hero.stat.companies": "Текстильных компаний",
    "hero.stat.rolls": "Отслеживаемых рулонов",
    "hero.stat.countries": "Стран",
    "hero.stat.industry": "В текстильной отрасли",
    "hero.feature.meters": "Метры",
    "hero.feature.rolls": "Рулоны",
    "hero.feature.colors": "Цвета",
    "hero.feature.cutting": "Раскрой",
    "hero.feature.warehouses": "Склады",
    "hero.feature.accounting": "Бухгалтерия",
    "hero.dashboard.revenue": "Выручка",
    "hero.dashboard.expenses": "Расходы",
    "hero.dashboard.profit": "Прибыль",
    "hero.dashboard.cash": "Денежный поток",
    "hero.dashboard.cashFlow": "Денежный поток",
    "hero.dashboard.orders": "Заказы",
    // Features
    "features.title": "Всё, что вам нужно",
    "features.subtitle": "Полная ERP-система для всех потребностей вашего бизнеса.",
    "features.allFeatures": "Все функции",
    "features.headerTitle": "Всё необходимое в одной системе",
    "features.headerSubtitle": "Полная ERP-система для всех потребностей вашего бизнеса от бухгалтерии до управления запасами и продажами",
    "features.exploreAll": "Изучить все функции",
    "features.barcode.title": "Продвинутый штрих-код",
    "features.barcode.desc": "Уникальный штрих-код для каждого рулона с полным отслеживанием от импорта до продажи.",
    "features.barcode.stat": "Полное отслеживание",
    "features.color.title": "Управление цветами",
    "features.color.desc": "Классификация тканей по цвету и оттенку с точным соответствием образцам.",
    "features.color.stat": "Умное соответствие",
    "features.fabric.title": "Ткань по метру и рулону",
    "features.fabric.desc": "Поддержка всех единиц измерения: метр, рулон, ярд, кг с автоконвертацией.",
    "features.fabric.stat": "Автоконвертация",
    "features.warehouse.title": "Мультисклад",
    "features.warehouse.desc": "Управление несколькими складами с указанием полки для каждого рулона.",
    "features.warehouse.stat": "Полное отслеживание",
    "features.accounting.title": "Полная бухгалтерия",
    "features.accounting.desc": "Полная система учёта для текстильной торговли с мультивалютностью.",
    "features.accounting.stat": "Финансовые отчёты",
    "features.ecommerce.title": "Интернет-магазин",
    "features.ecommerce.desc": "Готовый интернет-магазин БЕЗ дополнительных сборов за дизайн или настройку.",
    "features.ecommerce.stat": "Без доп. сборов",
    "features.reports": "Отчёты",
    "features.payments": "Платежи",
    "features.branches": "Филиалы",
    "features.analytics": "Аналитика",
    // Trust
    "trust.title": "Почему TexaCore?",
    // Pricing
    "pricing.title": "Выберите тариф",
    // Footer
    "footer.rights": "© 2024 TexaCore. Все права защищены.",
    // CTA
    "cta.ready": "Готовы начать?",
    "cta.button": "Начать сейчас",
    "cta.digitalTransformation": "Начните цифровую трансформацию",
    "cta.joinCompanies": "Присоединяйтесь к 500+ компаниям, использующим TexaCore для эффективного управления бизнесом",
    "cta.benefit1": "14 дней бесплатно",
    "cta.benefit2": "Без кредитной карты",
    "cta.benefit3": "Полный доступ ко всем функциям",
    "cta.contactSales": "Связаться с отделом продаж",
    "footer.transformBusiness": "Готовы преобразовать ваши бизнес-операции?",
    "footer.trustCompanies": "Присоединяйтесь к 500+ компаниям, доверяющим TexaCore",
    "footer.schedulDemo": "Запланировать демо",
    "footer.description": "Полная облачная ERP-система для современных предприятий. Доверяют 500+ компаний.",
    "footer.product": "Продукт",
    "footer.solutions": "Решения",
    "footer.company": "Компания",
    "footer.resources": "Ресурсы",
    "footer.newsletter": "Будьте в курсе",
    "footer.emailPlaceholder": "Ваш email",
    "footer.location": "Дублин, Ирландия",
    "footer.privacy": "Политика конфиденциальности",
    "footer.terms": "Условия использования",
    "footer.faq": "Частые вопросы",
    "footer.news": "Новости и обновления",
    "footer.about": "О нас",
    "footer.developedBy": "Все разработки TexaCore от",
    "footer.nextRevolutionTagline": "Глобальные программные решения из Ирландии — Обслуживаем предприятия по всему миру",
    // Global
    "global.learnMore": "Узнать больше",
    "global.getStarted": "Начать",
    "global.contactUs": "Связаться с нами",
    "global.startFree": "Начать бесплатно",
    "global.bookDemo": "Заказать демо",
    // Floating Button
    "floating.boostSales": "Увеличь продажи на 70%",
    "floating.seeTheDifference": "Узнай разницу",
  },
  uk: {
    // Navigation
    "nav.features": "Функції",
    "nav.pricing": "Ціни",
    "nav.contact": "Контакти",
    "nav.becomeAgent": "Стати агентом",
    "nav.solutions": "Рішення",
    "nav.industries": "Галузі",
    "nav.about": "Про нас",
    "nav.whyTexaCore": "Чому TexaCore?",
    "nav.workflow": "Процес",
    "nav.viewAllSolutions": "Усі",
    "nav.signIn": "Увійти",
    "nav.startFree": "Почати безкоштовно",
    "nav.selectLanguage": "Обрати мову",
    "nav.selectTheme": "Обрати тему",
    // Solution Links
    "solutions.containerTracking": "Відстеження контейнерів",
    "solutions.rollManagement": "Управління рулонами",
    "solutions.warehouseManagement": "Управління складом",
    "solutions.fabricManagement": "Управління тканинами",
    "solutions.posSystem": "POS система",
    "solutions.completeWorkflow": "Повний робочий процес",
    "solutions.ecommerce": "Інтернет-магазин",
    "solutions.crm": "CRM",
    "solutions.employeeManagement": "Управління персоналом",
    "solutions.accounting": "Бухгалтерія та прибуток",
    "solutions.fabricManufacturing": "Виробництво тканин",
    "solutions.garmentManufacturing": "Виробництво одягу",
    "solutions.aiAnalytics": "ШІ та аналітика",
    "solutions.reportsAnalytics": "Звіти та аналітика",
    "solutions.shipping": "Доставка",
    "solutions.agentsDealers": "Агенти та дилери",
    // Theme
    "theme.light": "Світла",
    "theme.dark": "Темна",
    "theme.auto": "Авто",
    // Hero
    "hero.title": "Перша ERP-система для текстильної галузі",
    "hero.subtitle": "Перша у світі система, розроблена спеціально для текстильних компаній. Підтримує метри, рулони, кольори, розкрій.",
    "hero.cta.demo": "Почати безкоштовно",
    "hero.cta.trial": "Дивитись демо",
    "hero.badge": "Перший вибір в Європі та Затоці",
    "hero.tagline": "Якість, гідна довіри",
    "hero.noCreditCard": "Без банківської картки",
    "hero.quickSetup": "Швидке налаштування",
    "hero.arabicSupport": "Підтримка арабської",
    "hero.stat.companies": "Текстильних компаній",
    "hero.stat.rolls": "Відстежуваних рулонів",
    "hero.stat.countries": "Країн",
    "hero.stat.industry": "У текстильній галузі",
    "hero.feature.meters": "Метри",
    "hero.feature.rolls": "Рулони",
    "hero.feature.colors": "Кольори",
    "hero.feature.cutting": "Розкрій",
    "hero.feature.warehouses": "Склади",
    "hero.feature.accounting": "Бухгалтерія",
    "hero.dashboard.revenue": "Дохід",
    "hero.dashboard.expenses": "Витрати",
    "hero.dashboard.profit": "Прибуток",
    "hero.dashboard.cash": "Грошовий потік",
    "hero.dashboard.cashFlow": "Грошовий потік",
    "hero.dashboard.orders": "Замовлення",
    // Features
    "features.title": "Все, що вам потрібно",
    "features.subtitle": "Повна ERP-система для всіх потреб вашого бізнесу.",
    "features.allFeatures": "Всі функції",
    "features.headerTitle": "Все необхідне в одній системі",
    "features.headerSubtitle": "Повна ERP-система для всіх потреб вашого бізнесу від бухгалтерії до управління запасами та продажами",
    "features.exploreAll": "Дослідити всі функції",
    "features.barcode.title": "Просунутий штрих-код",
    "features.barcode.desc": "Унікальний штрих-код для кожного рулону з повним відстеженням від імпорту до продажу.",
    "features.barcode.stat": "Повне відстеження",
    "features.color.title": "Управління кольорами",
    "features.color.desc": "Класифікація тканин за кольором та відтінком з точною відповідністю зразкам.",
    "features.color.stat": "Розумна відповідність",
    "features.fabric.title": "Тканина по метру та рулону",
    "features.fabric.desc": "Підтримка всіх одиниць виміру: метр, рулон, ярд, кг з автоконвертацією.",
    "features.fabric.stat": "Автоконвертація",
    "features.warehouse.title": "Мультисклад",
    "features.warehouse.desc": "Управління кількома складами з вказанням полиці для кожного рулону.",
    "features.warehouse.stat": "Повне відстеження",
    "features.accounting.title": "Повна бухгалтерія",
    "features.accounting.desc": "Повна система обліку для текстильної торгівлі з мультивалютністю.",
    "features.accounting.stat": "Фінансові звіти",
    "features.ecommerce.title": "Інтернет-магазин",
    "features.ecommerce.desc": "Готовий інтернет-магазин БЕЗ додаткових зборів за дизайн чи налаштування.",
    "features.ecommerce.stat": "Без дод. зборів",
    "features.reports": "Звіти",
    "features.payments": "Платежі",
    "features.branches": "Філії",
    "features.analytics": "Аналітика",
    // Trust
    "trust.title": "Чому TexaCore?",
    // Pricing
    "pricing.title": "Оберіть тариф",
    // Footer
    "footer.rights": "© 2024 TexaCore. Всі права захищені.",
    // CTA
    "cta.ready": "Готові почати?",
    "cta.button": "Почати зараз",
    "cta.digitalTransformation": "Почніть цифрову трансформацію",
    "cta.joinCompanies": "Приєднуйтесь до 500+ компаній, що використовують TexaCore для ефективного управління бізнесом",
    "cta.benefit1": "14 днів безкоштовно",
    "cta.benefit2": "Без кредитної картки",
    "cta.benefit3": "Повний доступ до всіх функцій",
    "cta.contactSales": "Зв'язатися з відділом продажів",
    "footer.transformBusiness": "Готові перетворити ваші бізнес-операції?",
    "footer.trustCompanies": "Приєднуйтесь до 500+ компаній, що довіряють TexaCore",
    "footer.schedulDemo": "Запланувати демо",
    "footer.description": "Повна хмарна ERP-система для сучасних підприємств. Довіряють 500+ компаній.",
    "footer.product": "Продукт",
    "footer.solutions": "Рішення",
    "footer.company": "Компанія",
    "footer.resources": "Ресурси",
    "footer.newsletter": "Будьте в курсі",
    "footer.emailPlaceholder": "Ваш email",
    "footer.location": "Дублін, Ірландія",
    "footer.privacy": "Політика конфіденційності",
    "footer.terms": "Умови використання",
    "footer.faq": "Часті питання",
    "footer.news": "Новини та оновлення",
    "footer.about": "Про нас",
    "footer.developedBy": "Усі розробки TexaCore від",
    "footer.nextRevolutionTagline": "Глобальні програмні рішення з Ірландії — Обслуговуємо підприємства по всьому світу",
    // Global
    "global.learnMore": "Дізнатись більше",
    "global.getStarted": "Почати",
    "global.contactUs": "Зв'язатись з нами",
    "global.startFree": "Почати безкоштовно",
    "global.bookDemo": "Замовити демо",
    // Floating Button
    "floating.boostSales": "Збільш продажі на 70%",
    "floating.seeTheDifference": "Дізнайся різницю",
  },
  ro: {
    // Navigation
    "nav.features": "Funcții",
    "nav.pricing": "Prețuri",
    "nav.contact": "Contact",
    "nav.becomeAgent": "Deveniți agent",
    "nav.solutions": "Soluții",
    "nav.industries": "Industrii",
    "nav.about": "Despre noi",
    "nav.whyTexaCore": "De ce TexaCore?",
    "nav.workflow": "Flux",
    "nav.viewAllSolutions": "Toate",
    "nav.signIn": "Conectare",
    "nav.startFree": "Începe gratuit",
    "nav.selectLanguage": "Alege limba",
    "nav.selectTheme": "Alege tema",
    // Solution Links
    "solutions.containerTracking": "Urmărire containere",
    "solutions.rollManagement": "Gestionare rulouri",
    "solutions.warehouseManagement": "Gestionare depozit",
    "solutions.fabricManagement": "Gestionare țesături",
    "solutions.posSystem": "Sistem POS",
    "solutions.completeWorkflow": "Flux de lucru complet",
    "solutions.ecommerce": "E-Commerce",
    "solutions.crm": "CRM",
    "solutions.employeeManagement": "Gestionare angajați",
    "solutions.accounting": "Contabilitate și profit",
    "solutions.fabricManufacturing": "Fabricare țesături",
    "solutions.garmentManufacturing": "Fabricare îmbrăcăminte",
    "solutions.aiAnalytics": "IA și analiză",
    "solutions.reportsAnalytics": "Rapoarte și analiză",
    "solutions.shipping": "Livrare",
    "solutions.agentsDealers": "Agenți și dealeri",
    // Theme
    "theme.light": "Luminos",
    "theme.dark": "Întunecat",
    "theme.auto": "Auto",
    // Hero
    "hero.title": "Primul sistem ERP pentru industria textilă",
    "hero.subtitle": "Primul sistem din lume conceput special pentru companiile textile. Suportă metri, role, culori, croială.",
    "hero.cta.demo": "Începe gratuit",
    "hero.cta.trial": "Vezi demo",
    "hero.badge": "Prima alegere în Europa și Golf",
    "hero.tagline": "Calitate demnă de încredere",
    "hero.noCreditCard": "Fără card bancar",
    "hero.quickSetup": "Configurare rapidă",
    "hero.arabicSupport": "Suport pentru arabă",
    "hero.stat.companies": "Companii textile",
    "hero.stat.rolls": "Role urmărite",
    "hero.stat.countries": "Țări",
    "hero.stat.industry": "În industria textilă",
    "hero.feature.meters": "Metri",
    "hero.feature.rolls": "Role",
    "hero.feature.colors": "Culori",
    "hero.feature.cutting": "Croială",
    "hero.feature.warehouses": "Depozite",
    "hero.feature.accounting": "Contabilitate",
    "hero.dashboard.revenue": "Venituri",
    "hero.dashboard.expenses": "Cheltuieli",
    "hero.dashboard.profit": "Profit",
    "hero.dashboard.cash": "Flux numerar",
    "hero.dashboard.cashFlow": "Flux numerar",
    "hero.dashboard.orders": "Comenzi",
    // Features
    "features.title": "Tot ce ai nevoie",
    "features.subtitle": "Sistem ERP complet pentru toate nevoile afacerii tale.",
    "features.allFeatures": "Toate funcțiile",
    "features.headerTitle": "Tot ce ai nevoie într-un singur sistem",
    "features.headerSubtitle": "Sistem ERP complet pentru toate nevoile afacerii tale de la contabilitate la gestionarea stocurilor și vânzărilor",
    "features.exploreAll": "Explorează toate funcțiile",
    "features.barcode.title": "Cod de bare avansat",
    "features.barcode.desc": "Cod de bare unic pentru fiecare rolă cu urmărire completă de la import la vânzare.",
    "features.barcode.stat": "Urmărire completă",
    "features.color.title": "Gestionare culori",
    "features.color.desc": "Clasificarea țesăturilor după culoare și nuanță cu potrivire precisă a mostrelor.",
    "features.color.stat": "Potrivire inteligentă",
    "features.fabric.title": "Țesătură pe metru și rolă",
    "features.fabric.desc": "Suportă toate unitățile de măsură: metru, rolă, yard, kg cu conversie automată.",
    "features.fabric.stat": "Conversie automată",
    "features.warehouse.title": "Multi-depozit",
    "features.warehouse.desc": "Gestionarea mai multor depozite cu locația raftului pentru fiecare rolă.",
    "features.warehouse.stat": "Urmărire completă",
    "features.accounting.title": "Contabilitate completă",
    "features.accounting.desc": "Sistem contabil complet conceput pentru comerțul cu textile cu multi-valută.",
    "features.accounting.stat": "Rapoarte financiare",
    "features.ecommerce.title": "Magazin online",
    "features.ecommerce.desc": "Magazin online gata FĂRĂ taxe suplimentare de design sau configurare.",
    "features.ecommerce.stat": "Fără taxe extra",
    "features.reports": "Rapoarte",
    "features.payments": "Plăți",
    "features.branches": "Filiale",
    "features.analytics": "Analiză",
    // Trust
    "trust.title": "De ce TexaCore?",
    // Pricing
    "pricing.title": "Alege planul",
    // Footer
    "footer.rights": "© 2024 TexaCore. Toate drepturile rezervate.",
    // CTA
    "cta.ready": "Gata de start?",
    "cta.button": "Începe acum",
    "cta.digitalTransformation": "Începe transformarea digitală",
    "cta.joinCompanies": "Alătură-te celor 500+ companii care folosesc TexaCore pentru a-și gestiona eficient afacerea",
    "cta.benefit1": "14 zile gratuit",
    "cta.benefit2": "Fără card de credit",
    "cta.benefit3": "Acces complet la toate funcțiile",
    "cta.contactSales": "Contactează vânzările",
    "footer.transformBusiness": "Gata să transformi operațiunile afacerii tale?",
    "footer.trustCompanies": "Alătură-te celor 500+ companii care au încredere în TexaCore",
    "footer.schedulDemo": "Programează demo",
    "footer.description": "Sistem ERP cloud complet pentru întreprinderile moderne. De încredere pentru 500+ companii.",
    "footer.product": "Produs",
    "footer.solutions": "Soluții",
    "footer.company": "Companie",
    "footer.resources": "Resurse",
    "footer.newsletter": "Fii la curent",
    "footer.emailPlaceholder": "Email-ul tău",
    "footer.location": "Dublin, Irlanda",
    "footer.privacy": "Politica de confidențialitate",
    "footer.terms": "Termeni și condiții",
    "footer.faq": "Întrebări frecvente",
    "footer.news": "Știri și actualizări",
    "footer.about": "Despre noi",
    "footer.developedBy": "Toate dezvoltările TexaCore de către",
    "footer.nextRevolutionTagline": "Soluții software globale din Irlanda — Deservim întreprinderi din întreaga lume",
    // Global
    "global.learnMore": "Află mai multe",
    "global.getStarted": "Începe",
    "global.contactUs": "Contactează-ne",
    "global.startFree": "Începe gratuit",
    "global.bookDemo": "Rezervă demo",
    // Floating Button
    "floating.boostSales": "Crește vânzările cu 70%",
    "floating.seeTheDifference": "Vezi diferența",
  },
  pl: {
    // Navigation
    "nav.features": "Funkcje",
    "nav.pricing": "Cennik",
    "nav.contact": "Kontakt",
    "nav.becomeAgent": "Zostań agentem",
    "nav.solutions": "Rozwiązania",
    "nav.industries": "Branże",
    "nav.about": "O nas",
    "nav.whyTexaCore": "Dlaczego TexaCore?",
    "nav.workflow": "Proces",
    "nav.viewAllSolutions": "Wszystkie",
    "nav.signIn": "Zaloguj się",
    "nav.startFree": "Zacznij za darmo",
    "nav.selectLanguage": "Wybierz język",
    "nav.selectTheme": "Wybierz motyw",
    // Solution Links
    "solutions.containerTracking": "Śledzenie kontenerów",
    "solutions.rollManagement": "Zarządzanie rolkami",
    "solutions.warehouseManagement": "Zarządzanie magazynem",
    "solutions.fabricManagement": "Zarządzanie tkaninami",
    "solutions.posSystem": "System POS",
    "solutions.completeWorkflow": "Pełny przepływ pracy",
    "solutions.ecommerce": "E-Commerce",
    "solutions.crm": "CRM",
    "solutions.employeeManagement": "Zarządzanie pracownikami",
    "solutions.accounting": "Księgowość i zyski",
    "solutions.fabricManufacturing": "Produkcja tkanin",
    "solutions.garmentManufacturing": "Produkcja odzieży",
    "solutions.aiAnalytics": "AI i analityka",
    "solutions.reportsAnalytics": "Raporty i analityka",
    "solutions.shipping": "Dostawa",
    "solutions.agentsDealers": "Agenci i dealerzy",
    // Theme
    "theme.light": "Jasny",
    "theme.dark": "Ciemny",
    "theme.auto": "Auto",
    // Hero
    "hero.title": "Pierwszy system ERP dla branży tekstylnej",
    "hero.subtitle": "Pierwszy na świecie system zaprojektowany specjalnie dla firm tekstylnych. Obsługuje metry, rolki, kolory, krojenie.",
    "hero.cta.demo": "Zacznij za darmo",
    "hero.cta.trial": "Zobacz demo",
    "hero.badge": "Pierwszy wybór w Europie i Zatoce",
    "hero.tagline": "Jakość godna zaufania",
    "hero.noCreditCard": "Bez karty kredytowej",
    "hero.quickSetup": "Szybka konfiguracja",
    "hero.arabicSupport": "Obsługa arabskiego",
    "hero.stat.companies": "Firm tekstylnych",
    "hero.stat.rolls": "Śledzonych rolek",
    "hero.stat.countries": "Krajów",
    "hero.stat.industry": "W branży tekstylnej",
    "hero.feature.meters": "Metry",
    "hero.feature.rolls": "Rolki",
    "hero.feature.colors": "Kolory",
    "hero.feature.cutting": "Krojenie",
    "hero.feature.warehouses": "Magazyny",
    "hero.feature.accounting": "Księgowość",
    "hero.dashboard.revenue": "Przychody",
    "hero.dashboard.expenses": "Wydatki",
    "hero.dashboard.profit": "Zysk",
    "hero.dashboard.cash": "Przepływ gotówki",
    "hero.dashboard.cashFlow": "Przepływ gotówki",
    "hero.dashboard.orders": "Zamówienia",
    // Features
    "features.title": "Wszystko, czego potrzebujesz",
    "features.subtitle": "Kompletny system ERP dla wszystkich potrzeb Twojej firmy.",
    "features.allFeatures": "Wszystkie funkcje",
    "features.headerTitle": "Wszystko, czego potrzebujesz w jednym systemie",
    "features.headerSubtitle": "Kompletny system ERP dla wszystkich potrzeb Twojej firmy od księgowości po zarządzanie zapasami i sprzedażą",
    "features.exploreAll": "Odkryj wszystkie funkcje",
    "features.barcode.title": "Zaawansowany kod kreskowy",
    "features.barcode.desc": "Unikalny kod kreskowy dla każdej rolki z pełnym śledzeniem od importu do sprzedaży.",
    "features.barcode.stat": "Pełne śledzenie",
    "features.color.title": "Zarządzanie kolorami",
    "features.color.desc": "Klasyfikacja tkanin według koloru i odcienia z precyzyjnym dopasowaniem próbek.",
    "features.color.stat": "Inteligentne dopasowanie",
    "features.fabric.title": "Tkanina na metr i rolkę",
    "features.fabric.desc": "Obsługuje wszystkie jednostki miary: metr, rolka, jard, kg z automatyczną konwersją.",
    "features.fabric.stat": "Automatyczna konwersja",
    "features.warehouse.title": "Multi-magazyn",
    "features.warehouse.desc": "Zarządzanie wieloma magazynami z lokalizacją półki dla każdej rolki.",
    "features.warehouse.stat": "Pełne śledzenie",
    "features.accounting.title": "Pełna księgowość",
    "features.accounting.desc": "Kompletny system księgowy zaprojektowany dla handlu tekstylnego z wielowalutowością.",
    "features.accounting.stat": "Raporty finansowe",
    "features.ecommerce.title": "Sklep internetowy",
    "features.ecommerce.desc": "Gotowy sklep internetowy BEZ dodatkowych opłat za design lub konfigurację.",
    "features.ecommerce.stat": "Bez dodatkowych opłat",
    "features.reports": "Raporty",
    "features.payments": "Płatności",
    "features.branches": "Oddziały",
    "features.analytics": "Analityka",
    // Trust
    "trust.title": "Dlaczego TexaCore?",
    // Pricing
    "pricing.title": "Wybierz plan",
    // Footer
    "footer.rights": "© 2024 TexaCore. Wszelkie prawa zastrzeżone.",
    // CTA
    "cta.ready": "Gotowy do startu?",
    "cta.button": "Zacznij teraz",
    "cta.digitalTransformation": "Rozpocznij cyfrową transformację",
    "cta.joinCompanies": "Dołącz do 500+ firm korzystających z TexaCore do efektywnego zarządzania biznesem",
    "cta.benefit1": "14 dni za darmo",
    "cta.benefit2": "Bez karty kredytowej",
    "cta.benefit3": "Pełny dostęp do wszystkich funkcji",
    "cta.contactSales": "Skontaktuj się ze sprzedażą",
    "footer.transformBusiness": "Gotowy do transformacji operacji biznesowych?",
    "footer.trustCompanies": "Dołącz do 500+ firm, które zaufały TexaCore",
    "footer.schedulDemo": "Umów demo",
    "footer.description": "Kompletny system ERP w chmurze dla nowoczesnych przedsiębiorstw. Zaufało nam 500+ firm.",
    "footer.product": "Produkt",
    "footer.solutions": "Rozwiązania",
    "footer.company": "Firma",
    "footer.resources": "Zasoby",
    "footer.newsletter": "Bądź na bieżąco",
    "footer.emailPlaceholder": "Twój email",
    "footer.location": "Dublin, Irlandia",
    "footer.privacy": "Polityka prywatności",
    "footer.terms": "Regulamin",
    "footer.faq": "FAQ",
    "footer.news": "Aktualności i aktualizacje",
    "footer.about": "O nas",
    "footer.developedBy": "Wszystkie rozwiązania TexaCore opracowane przez",
    "footer.nextRevolutionTagline": "Globalne rozwiązania software z Irlandii — Obsługujemy przedsiębiorstwa na całym świecie",
    // Global
    "global.learnMore": "Dowiedz się więcej",
    "global.getStarted": "Rozpocznij",
    "global.contactUs": "Skontaktuj się",
    "global.startFree": "Zacznij za darmo",
    "global.bookDemo": "Zarezerwuj demo",
    // Floating Button
    "floating.boostSales": "Zwiększ sprzedaż o 70%",
    "floating.seeTheDifference": "Zobacz różnicę",
  },
  it: {
    // Navigation
    "nav.features": "Funzionalità",
    "nav.pricing": "Prezzi",
    "nav.contact": "Contatti",
    "nav.becomeAgent": "Diventa agente",
    "nav.solutions": "Soluzioni",
    "nav.industries": "Settori",
    "nav.about": "Chi siamo",
    "nav.whyTexaCore": "Perché TexaCore?",
    "nav.workflow": "Flusso",
    "nav.viewAllSolutions": "Tutti",
    "nav.signIn": "Accedi",
    "nav.startFree": "Inizia gratis",
    "nav.selectLanguage": "Seleziona lingua",
    "nav.selectTheme": "Seleziona tema",
    // Solution Links
    "solutions.containerTracking": "Tracciamento container",
    "solutions.rollManagement": "Gestione rotoli",
    "solutions.warehouseManagement": "Gestione magazzino",
    "solutions.fabricManagement": "Gestione tessuti",
    "solutions.posSystem": "Sistema POS",
    "solutions.completeWorkflow": "Flusso di lavoro completo",
    "solutions.ecommerce": "E-Commerce",
    "solutions.crm": "CRM",
    "solutions.employeeManagement": "Gestione dipendenti",
    "solutions.accounting": "Contabilità e profitti",
    "solutions.fabricManufacturing": "Produzione tessuti",
    "solutions.garmentManufacturing": "Produzione abbigliamento",
    "solutions.aiAnalytics": "IA e analisi",
    "solutions.reportsAnalytics": "Report e analisi",
    "solutions.shipping": "Spedizione",
    "solutions.agentsDealers": "Agenti e rivenditori",
    // Theme
    "theme.light": "Chiaro",
    "theme.dark": "Scuro",
    "theme.auto": "Auto",
    // Hero
    "hero.title": "Il primo sistema ERP per l'industria tessile",
    "hero.subtitle": "Il primo sistema al mondo progettato specificamente per le aziende tessili. Supporta metri, rotoli, colori, taglio.",
    "hero.cta.demo": "Inizia gratis",
    "hero.cta.trial": "Guarda demo",
    "hero.badge": "Prima scelta in Europa e nel Golfo",
    "hero.tagline": "Qualità degna di fiducia",
    "hero.noCreditCard": "Senza carta di credito",
    "hero.quickSetup": "Configurazione rapida",
    "hero.arabicSupport": "Supporto arabo",
    "hero.stat.companies": "Aziende tessili",
    "hero.stat.rolls": "Rotoli tracciati",
    "hero.stat.countries": "Paesi",
    "hero.stat.industry": "Nel settore tessile",
    "hero.feature.meters": "Metri",
    "hero.feature.rolls": "Rotoli",
    "hero.feature.colors": "Colori",
    "hero.feature.cutting": "Taglio",
    "hero.feature.warehouses": "Magazzini",
    "hero.feature.accounting": "Contabilità",
    "hero.dashboard.revenue": "Ricavi",
    "hero.dashboard.expenses": "Spese",
    "hero.dashboard.profit": "Profitto",
    "hero.dashboard.cash": "Flusso di cassa",
    "hero.dashboard.cashFlow": "Flusso di cassa",
    "hero.dashboard.orders": "Ordini",
    // Features
    "features.title": "Tutto ciò di cui hai bisogno",
    "features.subtitle": "Sistema ERP completo per tutte le esigenze della tua azienda.",
    "features.allFeatures": "Tutte le funzionalità",
    "features.headerTitle": "Tutto ciò di cui hai bisogno in un unico sistema",
    "features.headerSubtitle": "Sistema ERP completo per tutte le esigenze della tua azienda dalla contabilità alla gestione dell'inventario e delle vendite",
    "features.exploreAll": "Esplora tutte le funzionalità",
    "features.barcode.title": "Codice a barre avanzato",
    "features.barcode.desc": "Codice a barre unico per ogni rotolo con tracciamento completo dall'importazione alla vendita.",
    "features.barcode.stat": "Tracciamento completo",
    "features.color.title": "Gestione colori",
    "features.color.desc": "Classificazione dei tessuti per colore e tonalità con corrispondenza precisa dei campioni.",
    "features.color.stat": "Corrispondenza intelligente",
    "features.fabric.title": "Tessuto al metro e rotolo",
    "features.fabric.desc": "Supporta tutte le unità di misura: metro, rotolo, yard, kg con conversione automatica.",
    "features.fabric.stat": "Conversione automatica",
    "features.warehouse.title": "Multi-magazzino",
    "features.warehouse.desc": "Gestione di più magazzini con posizione scaffale per ogni rotolo.",
    "features.warehouse.stat": "Tracciamento completo",
    "features.accounting.title": "Contabilità completa",
    "features.accounting.desc": "Sistema contabile completo progettato per il commercio tessile con multi-valuta.",
    "features.accounting.stat": "Report finanziari",
    "features.ecommerce.title": "Negozio online",
    "features.ecommerce.desc": "Negozio online pronto SENZA costi aggiuntivi di design o configurazione.",
    "features.ecommerce.stat": "Nessun costo extra",
    "features.reports": "Report",
    "features.payments": "Pagamenti",
    "features.branches": "Filiali",
    "features.analytics": "Analisi",
    // Trust
    "trust.title": "Perché TexaCore?",
    // Pricing
    "pricing.title": "Scegli il piano",
    // Footer
    "footer.rights": "© 2024 TexaCore. Tutti i diritti riservati.",
    // CTA
    "cta.ready": "Pronto per iniziare?",
    "cta.button": "Inizia ora",
    "cta.digitalTransformation": "Inizia la tua trasformazione digitale",
    "cta.joinCompanies": "Unisciti a oltre 500 aziende che utilizzano TexaCore per gestire la propria attività in modo efficiente",
    "cta.benefit1": "14 giorni gratis",
    "cta.benefit2": "Senza carta di credito",
    "cta.benefit3": "Accesso completo a tutte le funzionalità",
    "cta.contactSales": "Contatta le vendite",
    "footer.transformBusiness": "Pronto a trasformare le tue operazioni aziendali?",
    "footer.trustCompanies": "Unisciti a oltre 500 aziende che si fidano di TexaCore",
    "footer.schedulDemo": "Prenota una demo",
    "footer.description": "Sistema ERP cloud completo per le imprese moderne. Affidato da oltre 500 aziende.",
    "footer.product": "Prodotto",
    "footer.solutions": "Soluzioni",
    "footer.company": "Azienda",
    "footer.resources": "Risorse",
    "footer.newsletter": "Resta aggiornato",
    "footer.emailPlaceholder": "La tua email",
    "footer.location": "Dublino, Irlanda",
    "footer.privacy": "Informativa sulla privacy",
    "footer.terms": "Termini di servizio",
    "footer.faq": "FAQ",
    "footer.news": "Notizie e aggiornamenti",
    "footer.about": "Chi siamo",
    "footer.developedBy": "Tutti gli sviluppi TexaCore da",
    "footer.nextRevolutionTagline": "Soluzioni software globali dall'Irlanda — Al servizio delle imprese di tutto il mondo",
    // Global
    "global.learnMore": "Scopri di più",
    "global.getStarted": "Inizia",
    "global.contactUs": "Contattaci",
    "global.startFree": "Inizia gratis",
    "global.bookDemo": "Prenota demo",
    // Floating Button
    "floating.boostSales": "Vendite +70%",
    "floating.seeTheDifference": "Scopri la differenza",
  },
  fr: {
    // Navigation
    "nav.features": "Fonctionnalités",
    "nav.pricing": "Tarifs",
    "nav.contact": "Contact",
    "nav.becomeAgent": "Devenir agent",
    "nav.solutions": "Solutions",
    "nav.industries": "Industries",
    "nav.about": "À propos",
    "nav.whyTexaCore": "Pourquoi TexaCore?",
    "nav.workflow": "Workflow",
    "nav.viewAllSolutions": "Voir tout",
    "nav.signIn": "Connexion",
    "nav.startFree": "Essai gratuit",
    "nav.selectLanguage": "Langue",
    "nav.selectTheme": "Thème",
    // Basic keys fallback to English for now
    "global.bookDemo": "Réserver démo",
    "floating.boostSales": "Ventes +70%",
    "floating.seeTheDifference": "Voir la différence",
  },
  de: {
    // Navigation
    "nav.features": "Funktionen",
    "nav.pricing": "Preise",
    "nav.contact": "Kontakt",
    "nav.becomeAgent": "Agent werden",
    "nav.solutions": "Lösungen",
    "nav.industries": "Branchen",
    "nav.about": "Über uns",
    "nav.whyTexaCore": "Warum TexaCore?",
    "nav.workflow": "Workflow",
    "nav.viewAllSolutions": "Alle anzeigen",
    "nav.signIn": "Anmelden",
    "nav.startFree": "Kostenlos starten",
    "nav.selectLanguage": "Sprache",
    "nav.selectTheme": "Design",
    "global.bookDemo": "Demo buchen",
    "floating.boostSales": "Umsatz +70%",
    "floating.seeTheDifference": "Unterschied sehen",
  },
  nl: {
    // Navigation
    "nav.features": "Functies",
    "nav.pricing": "Prijzen",
    "nav.contact": "Contact",
    "nav.becomeAgent": "Word agent",
    "nav.solutions": "Oplossingen",
    "nav.industries": "Sectoren",
    "nav.about": "Over ons",
    "nav.whyTexaCore": "Waarom TexaCore?",
    "nav.workflow": "Workflow",
    "nav.viewAllSolutions": "Alles bekijken",
    "nav.signIn": "Inloggen",
    "nav.startFree": "Gratis starten",
    "nav.selectLanguage": "Taal",
    "nav.selectTheme": "Thema",
    "global.bookDemo": "Demo boeken",
    "floating.boostSales": "Verkoop +70%",
    "floating.seeTheDifference": "Zie het verschil",
  },
  tr: {
    // Navigation
    "nav.features": "Özellikler",
    "nav.pricing": "Fiyatlar",
    "nav.contact": "İletişim",
    "nav.becomeAgent": "Acente olun",
    "nav.solutions": "Çözümler",
    "nav.industries": "Sektörler",
    "nav.about": "Hakkımızda",
    "nav.whyTexaCore": "Neden TexaCore?",
    "nav.workflow": "Akış",
    "nav.viewAllSolutions": "Tümü",
    "nav.signIn": "Giriş Yap",
    "nav.startFree": "Ücretsiz Başla",
    "nav.selectLanguage": "Dil Seç",
    "nav.selectTheme": "Tema Seç",
    // Solution Links
    "solutions.containerTracking": "Konteyner Takibi",
    "solutions.rollManagement": "Rulo Yönetimi",
    "solutions.warehouseManagement": "Depo Yönetimi",
    "solutions.fabricManagement": "Kumaş Yönetimi",
    "solutions.posSystem": "POS Sistemi",
    "solutions.completeWorkflow": "Tam İş Akışı",
    "solutions.ecommerce": "E-Ticaret",
    "solutions.crm": "CRM",
    "solutions.employeeManagement": "Çalışan Yönetimi",
    "solutions.accounting": "Muhasebe ve Kar",
    "solutions.fabricManufacturing": "Kumaş Üretimi",
    "solutions.garmentManufacturing": "Giysi Üretimi",
    "solutions.aiAnalytics": "Yapay Zeka ve Analiz",
    "solutions.reportsAnalytics": "Raporlar ve Analiz",
    "solutions.shipping": "Kargo ve Teslimat",
    "solutions.agentsDealers": "Acenteler ve Bayiler",
    // Theme
    "theme.light": "Açık",
    "theme.dark": "Koyu",
    "theme.auto": "Otomatik",
    // Hero
    "hero.title": "Tekstil sektörü için ilk ERP sistemi",
    "hero.subtitle": "Tekstil şirketleri için özel olarak tasarlanmış dünyanın ilk sistemi. Metre, rulo, renk, kesim destekler.",
    "hero.cta.demo": "Ücretsiz başla",
    "hero.cta.trial": "Demo izle",
    "hero.badge": "Avrupa ve Körfez'de ilk tercih",
    "hero.tagline": "Güvene değer kalite",
    "hero.noCreditCard": "Kredi kartı gerekmez",
    "hero.quickSetup": "Hızlı kurulum",
    "hero.arabicSupport": "Arapça desteği",
    "hero.stat.companies": "Tekstil Şirketi",
    "hero.stat.rolls": "İzlenen Rulo",
    "hero.stat.countries": "Ülke",
    "hero.stat.industry": "Tekstil Sektöründe",
    "hero.feature.meters": "Metreler",
    "hero.feature.rolls": "Rulolar",
    "hero.feature.colors": "Renkler",
    "hero.feature.cutting": "Kesim",
    "hero.feature.warehouses": "Depolar",
    "hero.feature.accounting": "Muhasebe",
    "hero.dashboard.revenue": "Gelir",
    "hero.dashboard.expenses": "Giderler",
    "hero.dashboard.profit": "Kar",
    "hero.dashboard.cash": "Nakit Akışı",
    "hero.dashboard.cashFlow": "Nakit Akışı",
    "hero.dashboard.orders": "Siparişler",
    // Features
    "features.title": "İhtiyacınız olan her şey",
    "features.subtitle": "İşletmenizin tüm ihtiyaçları için eksiksiz ERP sistemi.",
    "features.allFeatures": "Tüm Özellikler",
    "features.headerTitle": "Tek bir sistemde ihtiyacınız olan her şey",
    "features.headerSubtitle": "İşletmenizin tüm ihtiyaçları için muhasebeyen envanter ve satış yönetimine kadar eksiksiz ERP sistemi",
    "features.exploreAll": "Tüm özellikleri keşfet",
    "features.barcode.title": "Gelişmiş Barkod",
    "features.barcode.desc": "Her rulo için benzersiz barkod ile ithalattan satışa kadar tam takip.",
    "features.barcode.stat": "Tam Takip",
    "features.color.title": "Renk Yönetimi",
    "features.color.desc": "Kumaşların renk ve tona göre sınıflandırılması ile hassas numune eşleştirmesi.",
    "features.color.stat": "Akıllı Eşleştirme",
    "features.fabric.title": "Metre ve Rulo ile Kumaş",
    "features.fabric.desc": "Tüm ölçü birimleri desteklenir: metre, rulo, yard, kg otomatik dönüşüm ile.",
    "features.fabric.stat": "Otomatik Dönüşüm",
    "features.warehouse.title": "Çoklu Depo",
    "features.warehouse.desc": "Her rulo için raf konumu ile birden fazla depo yönetimi.",
    "features.warehouse.stat": "Tam Takip",
    "features.accounting.title": "Tam Muhasebe",
    "features.accounting.desc": "Çoklu para birimi ile tekstil ticareti için tasarlanmış tam muhasebe sistemi.",
    "features.accounting.stat": "Finansal Raporlar",
    "features.ecommerce.title": "E-ticaret Mağazası",
    "features.ecommerce.desc": "Tasarım veya kurulum ücreti OLMADAN hazır e-ticaret mağazası.",
    "features.ecommerce.stat": "Ekstra Ücret Yok",
    "features.reports": "Raporlar",
    "features.payments": "Ödemeler",
    "features.branches": "Şubeler",
    "features.analytics": "Analiz",
    // Trust
    "trust.title": "Neden TexaCore?",
    // Pricing
    "pricing.title": "Planınızı seçin",
    // Footer
    "footer.rights": "© 2024 TexaCore. Tüm hakları saklıdır.",
    // CTA
    "cta.ready": "Başlamaya hazır mısınız?",
    "cta.button": "Şimdi başla",
    "cta.digitalTransformation": "Dijital dönüşümünüzü başlatın",
    "cta.joinCompanies": "İşlerini verimli yönetmek için TexaCore kullanan 500+ şirkete katılın",
    "cta.benefit1": "14 gün ücretsiz",
    "cta.benefit2": "Kredi kartı gerekmez",
    "cta.benefit3": "Tüm özelliklere tam erişim",
    "cta.contactSales": "Satışla iletişime geç",
    "footer.transformBusiness": "İş operasyonlarınızı dönüştürmeye hazır mısınız?",
    "footer.trustCompanies": "TexaCore'e güvenen 500+ şirkete katılın",
    "footer.schedulDemo": "Demo Planla",
    "footer.description": "Modern işletmeler için eksiksiz bulut ERP sistemi. 500+ şirket tarafından güvenilir.",
    "footer.product": "Ürün",
    "footer.solutions": "Çözümler",
    "footer.company": "Şirket",
    "footer.resources": "Kaynaklar",
    "footer.newsletter": "Güncel Kalın",
    "footer.emailPlaceholder": "E-posta adresiniz",
    "footer.location": "Dublin, İrlanda",
    "footer.privacy": "Gizlilik Politikası",
    "footer.terms": "Kullanım Şartları",
    "footer.faq": "SSS",
    "footer.news": "Haberler ve Güncellemeler",
    "footer.about": "Hakkımızda",
    "footer.developedBy": "Tüm TexaCore geliştirmeleri",
    "footer.nextRevolutionTagline": "İrlanda'dan Global Yazılım Çözümleri — Dünya Genelinde İşletmelere Hizmet Veriyoruz",
    // Global
    "global.learnMore": "Daha fazla bilgi",
    "global.getStarted": "Başla",
    "global.contactUs": "Bize ulaşın",
    "global.startFree": "Ücretsiz başla",
    "global.bookDemo": "Demo rezervasyonu",
    // Floating Button
    "floating.boostSales": "Satışları %70 Artır",
    "floating.seeTheDifference": "Farkı gör",
  },
};

const LANGUAGE_STORAGE_KEY = "texacore-language";
const SITE_STORAGE_KEY = "texacore-site";

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem(LANGUAGE_STORAGE_KEY);
      if (saved && Object.keys(languageNames).includes(saved)) {
        return saved as Language;
      }
    }
    return "en";
  });
  
  const [siteId, setSiteIdState] = useState<SiteId>(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem(SITE_STORAGE_KEY);
      if (saved && ["texafab", "fincore", "dubai-stroy", "nextrev", "exchange"].includes(saved)) {
        return saved as SiteId;
      }
    }
    return "texafab";
  });

  const dir = rtlLanguages.includes(language) ? "rtl" : "ltr";

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== "undefined") {
      localStorage.setItem(LANGUAGE_STORAGE_KEY, lang);
    }
  };

  const toggleLanguage = () => {
    const langs = Object.keys(languageNames) as Language[];
    const currentIndex = langs.indexOf(language);
    const nextIndex = (currentIndex + 1) % langs.length;
    setLanguage(langs[nextIndex]);
  };

  // Apply RTL/LTR direction immediately on mount and on changes
  useEffect(() => {
    // Apply to document root
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
    document.documentElement.setAttribute("dir", dir);
    
    // Also apply to body for better RTL support
    document.body.dir = dir;
    document.body.setAttribute("dir", dir);
    document.body.style.direction = dir;
    document.body.style.textAlign = dir === "rtl" ? "right" : "left";
    
    // Add class for CSS targeting
    if (dir === "rtl") {
      document.documentElement.classList.add("rtl");
      document.documentElement.classList.remove("ltr");
      document.body.classList.add("rtl");
      document.body.classList.remove("ltr");
    } else {
      document.documentElement.classList.add("ltr");
      document.documentElement.classList.remove("rtl");
      document.body.classList.add("ltr");
      document.body.classList.remove("rtl");
    }
  }, [dir, language]);

  const t = (key: string) => {
    return translations[language][key] || translations.en[key] || key;
  };
  
  const setSiteId = (id: SiteId) => {
    setSiteIdState(id);
    if (typeof window !== "undefined") {
      localStorage.setItem(SITE_STORAGE_KEY, id);
    }
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t, dir, isRTL: dir === "rtl", siteId, setSiteId }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    // Return default values when outside provider (for storyboards and isolated rendering)
    return {
      language: "en" as Language,
      setLanguage: () => {},
      toggleLanguage: () => {},
      t: (key: string) => translations.en[key] || key,
      dir: "ltr" as const,
      isRTL: false,
      siteId: "texafab" as SiteId,
      setSiteId: () => {},
    };
  }
  return context;
}
